---
title: "Chart Collection"
author: "Allison O'Connor"
date: "November 22, 2014"
output: html_document
---

Here is where I am collecting all my charts until I decide where they need to go in the final project.

Between 1700s and 1890s, very few houses in Fairfax County were built with no fireplace.

```{r message = FALSE}
source("houses.R")
ggplot(data = FFX_res_data_sum,
  aes(x = decade, y = n, fill = has_fp)) + 
  geom_bar(stat="identity", position="dodge") +
  xlim(1700, 1899) +
  ylim (0, 16)

```

Between 1900s and 1940s, we see the following:

```{r message = FALSE}
source("houses.R")
ggplot(data = FFX_res_data_sum,
  aes(x = decade, y = n, fill = has_fp)) + 
  geom_bar(stat="identity", position="dodge") +
  xlim(1900, 1950) +
  ylim(0, 10000)


ggplot(FFX_res_data_fp, aes(decade)) +
  geom_freqpoly(aes(group = has_fireplace, colour = has_fireplace)) +
  xlim(1900, 1950) +
  ylim(0, 10000)
```

From 1950 to 2010 we see the following:

```{r message = FALSE}
source("houses.R")
ggplot(data = FFX_res_data_sum,
  aes(x = decade, y = n, fill = has_fp)) + 
  geom_bar(stat="identity", position="dodge") +
  xlim(1950, 2010)

ggplot(FFX_res_data_fp, aes(decade)) +
  geom_freqpoly(aes(group = has_fireplace, colour = has_fireplace)) +
  xlim(1950, 2010) 
  
```

```{r}
source("fp_per_house.R")
ggplot (data = FFX_number_fp_per_house,
        aes(x = decade, y = percentage, shape = fireplaces))+
  geom_point()
```